language: node_js
node_js:
- 8.11.4
script:
- npm run lint
- npm run test:coverage && cat test-coverage/lcov.info | node_modules/.bin/coveralls
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: ram@hiddentao.com
  api_key:
    secure: lGZCc3huDYx2+0OWbwqHaiABNKyT9XPzvad9buAjFh0mZH8i7jPq+NsBMAj1F/MuHnfcBSfm9N6r9tVkttljvGYyrgunTtoqFq1p5M1sMJU5FQ2oNANHENWaoJtCS35TK1zT17KzRgULEq4kBHTTv51gMzPGki3gWHpqlh1p4Qrnjjk2uv3OtK0MSSph4j+TJa5bQG22FADVOf1NoIZABmWvqtdb85Qgv/XOR7EZu7kL26gcLp2yG8ozPjLgtKk7ForO0FtyENWwmsTrOuhs/bZ0HxynxvGW6qFTA7DNC0GvHSKfnBpmb5P1sd6f9PVhqbWvtno9R+VYCGF5ueABE3899Vfcdm2M2eQnGw4kJihryj9wkz18GyTLW0bfjlhsHx1eC1GOv9Nb0NNntuaPdiISb1BOyWvkuoedFSyfo6wsohNzuSy6r5d/KrR9FFTylvxxV1FsPom9taajWg6OCxwyTBLqCqOrdX5GE4mNtBVgPfRtyWDs541vi7xXaNhOppJD2lTho3HvOva6rQmzLrlYxs+/y1ZJfifHOLBHV1kp4mKLSRJ+ER2oaAHfA/nMwrvgyunLPixQEXM0AwCYAbbYu5hEsbLOkBXOFYXwgrzAOxfLB/F8LdZHFRy556K1oSSPiCfvK5Z+m39nf+mJamZJyfUdnjYhhux1dF70xhI=
  on:
    tags: true
    repo: hiddentao/ethval
